name: mcp dev viirs deployment

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-west-2

# See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow
permissions:
  id-token: write # required for requesting the JWT
  contents: read  # required for actions/checkout

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.13]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox

      - name: Run Tox test environment
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  mcp-dev-viirs-deployment:
    strategy:
      matrix:
        python: [3.13]
    runs-on: ubuntu-latest
    needs: [unit-tests]
    environment:
      name: mcp-dev-viirs
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME_ARN }}
          role-session-name: ${{ github.actor }}
          aws-region: us-west-2

      - name: Convert secrets and vars to environment variables
        shell: python
        run: |
          import os

          secrets_and_vars = {
              **${{ toJson(secrets) }},
              **${{ toJson(vars) }},
          }

          with open(os.environ["GITHUB_ENV"], "a") as env_file:
              for name, value in secrets_and_vars.items():
                  # If the value contains a newline, use the delimiter syntax
                  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#multiline-strings
                  if "\n" in value:
                      print(f"{name}<<EOF\n{value}\nEOF", file=env_file)
                  else:
                      # Standard format for single lines
                      print(f"{name}={value}", file=env_file)

      - name: Deploy with tox
        run: tox -v -e dev -r -- deploy --require-approval never

      - name: Run DB setup
        run: |
          setupdb=$(aws cloudformation describe-stacks \
            --stack-name $HLS_STACKNAME \
            --query "Stacks[0].Outputs[?OutputKey=='setupdbexport'].OutputValue" \
            --output=text
          )
          aws lambda invoke --function-name=$setupdb response.json
